### ISSUE TITLE
what is the max sampling rate of rssi ?

### ISSUE THREAD

**Issue by desword** [kugg/wifirssi#9]
what is the max sampling rate of rssi ?
as shown in title and is there any way to change this sampling rate?

**Comment by kugg** [comment]
In the function start(): you can change the call to self.plt.pause(0.3) in to something lower like self.plt.pause(0.15) this will collect one sample per 0.15 seconds.
I had minor performance and UI glitch problems when going under 0.1, but it could be due to old versions of matplotlib. Good luck!

**Comment by desword** [comment]
thanks for help again!
